services:
  postgres:
    image: postgres:13.22-bookworm
    container_name: airflow-sandbox-pg
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.10.5
    container_name: airflow-sandbox-webserver
    command: airflow webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    volumes:
      - ./dags:/opt/airflow/dags
      #- ./airflow_logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.10.5
    container_name: airflow-sandbox-scheduler
    command: airflow scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    volumes:
      - ./dags:/opt/airflow/dags
      #- ./airflow_logs:/opt/airflow/logs
    depends_on:
      - postgres

volumes:
  pg_data:
  #airflow_logs: